### ISSUE TITLE
shodan模块__init__方法无法正确校验token

### ISSUE THREAD

**Issue by ST0new** [knownsec/pocsuite3#116]
![image](https://user-images.githubusercontent.com/45659593/81269050-5b93a000-907b-11ea-883f-a5f6872e657c.png)
在函数定义行中给token='我的api'，运行框架，出现token无效，让重新输入。
在self.token=‘apiToken’中修改token为自己的token后，仍然出现这个问题。
截图如下：
![image](https://user-images.githubusercontent.com/45659593/81269374-c93fcc00-907b-11ea-866c-1cd348a9aacc.png)

**Comment by zrquan** [comment]
可能是网络问题导致 token 验证失败了

**Comment by Becivells** [comment]
网络超时。最近内网访问 shodan 问题很多。数据稍微大一些，都会被中止
