### ISSUE TITLE
Hook requests导致在未初始化pocsuite3的情况下，使用requests出错

### ISSUE THREAD

**Issue by Ricky-Hao** [knownsec/pocsuite3#132]
具体问题在这一行，若是没有初始化`pocsuite3`的话，使用`requests`时会出现`KeyError`错误。
https://github.com/knownsec/pocsuite3/blob/53c3d9a9eb308c17f584f7ba1d2d03ca26c26129/pocsuite3/lib/request/patch/hook_request.py#L18
```python
File "/usr/local/lib/python3.8/site-packages/pocsuite3/lib/request/patch/hook_request.py", line 18, in session_request
    if conf.random_agent:
  File "/usr/local/lib/python3.8/site-packages/pocsuite3/lib/core/datatype.py", line 20, in __getattr__
    raise AttributeError(name)
AttributeError: random_agent
```
希望能够提供对`conf.random_agent`这里提供一个默认值？
或者在`AttributeDict.__getattr__`这里提供一个**压制报错，返回`None`**的功能。
https://github.com/knownsec/pocsuite3/blob/53c3d9a9eb308c17f584f7ba1d2d03ca26c26129/pocsuite3/lib/core/datatype.py#L18

**Comment by boy-hack** [comment]
在代码中加一行
```python
from pocsuite3 import init_pocsuite
init_pocsuite()
```
这个也不影响其他代码的使用

**Comment by Ricky-Hao** [comment]
我认为这种全局类的patch应该像gevent那样按需使用？如果不自动patch而且提供patch函数会不会更好点？

**Comment by Ricky-Hao** [comment]
既然要求使用`init_pocsuite()`，那么是hook放在这个里面会不会更恰当？或者单独提供一个函数

**Comment by boy-hack** [comment]
使用了pocsuite就会hook request了，这是无法避免的

**Comment by Ricky-Hao** [comment]
* 使用pocsuite3必然hook request
* 使用pocsuite3必须调用`init_pocsuite()`

那么应该是能够在`init_pocsuite()`里进行hook request的吧？
把hook放在`init_pocsuite()`里，如果使用pocsuite就运行`init_pocsuite()`，如果不使用则不运行，这样是不是对一个项目的其他部分代码更友好点？（避免不必要的hook，毕竟直接全局hook可能会有潜在的问题）

**Comment by boy-hack** [comment]
thanks,这种方式确实比较友好，已经修改到了这种方式
