### ISSUE TITLE
封装后，出现调用临时文件的BUG

### ISSUE THREAD

**Issue by Martin2877** [knownsec/pocsuite3#151]
![image](https://user-images.githubusercontent.com/26109420/102246613-f02b7e00-3f39-11eb-9b8c-e0d26f29060a.png)

**Comment by boy-hack** [comment]
这不是pocsuite的bug，你应该重点看看pyinstaller，打包时是否包含了pocsuite3

**Comment by Martin2877** [comment]
已FIX，发现是 pyinstaller 的坑，
需要 spec 文件中加入：
```
datas=[('./env/lib/python3.6/site-packages/pocsuite3','pocsuite3')],
```
