### ISSUE TITLE
bug ..

### ISSUE THREAD

**Issue by f5gkw** [knownsec/pocsuite3#152]
I am not easy with use of github.

I had installed pocsuite ( pip3 install pocsuite ) on kali and rapsberry.
the python version is 3.9.
Path is ok ( made export path).

when  I type:    pocsuite --version
           I get:

 File "/home/kali/.local/bin/pocsuite", line 5, in <module>
    from pocsuite.pocsuite_cli import main
  File "/home/kali/.local/lib/python3.9/site-packages/pocsuite/pocsuite_cli.py", line 196
    except Exception, ex:
                    ^
SyntaxError: invalid syntax

thanks for help,
Happy Christmas and new  year

**Comment by Ro0tk1t** [comment]
what you used is the old version, u can uninstall this & install latest version via :
```bash
$ pip3 uninstall pocsuite
$ pip3 install pocsuite3
```

**Comment by f5gkw** [comment]
> what you used is the old version, u can uninstall this & install latest version via :
> 
> ```shell
> $ pip3 uninstall pocsuite
> $ pip3 install pocsuite3
> ```

**Big Thanks !** 
I got the correct version.
Happy new year
