### ISSUE TITLE
pocsuite3/lib/core/interpreter.py 第71行有一个语法错误，把=错打成了:

### ISSUE THREAD

**Issue by Eattttt** [knownsec/pocsuite3#159]
![image](https://user-images.githubusercontent.com/28709155/105949283-68dc3900-60a7-11eb-8423-7e6abe855e2b.png)

**Comment by boy-hack** [comment]
在`1.7.3`修复了，更新到pocsuite3最新版本即可

**Comment by MrMetatron** [comment]
当然，在这里使用":="也许不是很明智的选择，但这确实不是语法错误，这是python3.8新增的合法表达式，详细信息可看[PEP572](https://www.python.org/dev/peps/pep-0572/)

**Comment by Eattttt** [comment]
@MrMetatron 感谢！
