### ISSUE TITLE
plugins文件中的poc_from_pocs.py的16行里的POCSUITE_POCS_PATH在哪里，有人知道吗？

### ISSUE THREAD

**Issue by niuyuxuan** [knownsec/pocsuite3#164]

**Comment by pokejeff** [comment]
POCSUITE_POCS_PATH是在lib/core/common.py的paths.POCSUITE_POCS_PATH = os.path.join(paths.POCSUITE_ROOT_PATH, "pocs")语句中赋值的。其实直接从变量名中就可以知道这个变量指的是pocs目录所在的位置

**Comment by niuyuxuan** [comment]
那我ctrul+单击为什么没有反应呢？


---原始邮件---
发件人: &quot;kui&quot;<notifications@github.com&gt;
发送时间: 2021年3月3日(周三) 晚上7:21
收件人: &quot;knownsec/pocsuite3&quot;<pocsuite3@noreply.github.com&gt;;
抄送: &quot;niuyuxuan&quot;<1157472218@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题: Re: [knownsec/pocsuite3] plugins文件中的poc_from_pocs.py的16行里的POCSUITE_POCS_PATH在哪里，有人知道吗？ (#164)




 
POCSUITE_POCS_PATH是在lib/core/common.py的paths.POCSUITE_POCS_PATH = os.path.join(paths.POCSUITE_ROOT_PATH, "pocs")语句中赋值的。其实直接从变量名中就可以知道这个变量指的是pocs目录所在的位置
 
&mdash;

**Comment by pokejeff** [comment]
因为paths变量是AttribDict()类，POCSUITE_ROOT_PATH并不是它的属性。如果没有其他问题的话请关闭这个issue
