### ISSUE TITLE
自己改写poc_from_pocs中的路径加载不出来，改写处为图中标蓝

### ISSUE THREAD

**Issue by niuyuxuan** [knownsec/pocsuite3#168]
![微信图片_20210304172617](https://user-images.githubusercontent.com/40338208/109942691-66f13f80-7d0f-11eb-8aa0-cb2b5cd00b18.jpg)

**Comment by LoRexxar** [comment]
这都是你自己写的啊...你要自己研究为啥啊，调试报错...

非工具本身运行的bug就不要发issue，可以自己多研究研究
