### ISSUE TITLE
Shodan加载的坑

### ISSUE THREAD

**Issue by whinamax** [knownsec/pocsuite3#17]
\pocsuite3\plugins\target_from_shodan.py
`class TargetFromShodan(PluginBase):
    category = PLUGIN_TYPE.TARGETS

    def init_shodan_api(self):
        self.shodan = Shodan()
        if self.shodan.get_resource_info():
            info_msg = "shodan credits limit {0}".format(self.shodan.credits)
            logger.info(info_msg)

    def init(self):
        self.init_shodan_api()
`
其中init(self)应更正为   \_\_init\_\_(self)
不知道

**Comment by whinamax** [comment]
> \pocsuite3\plugins\target_from_shodan.py
> `class TargetFromShodan(PluginBase):
> category = PLUGIN_TYPE.TARGETS
> 
> ```
> def init_shodan_api(self):
>     self.shodan = Shodan()
>     if self.shodan.get_resource_info():
>         info_msg = "shodan credits limit {0}".format(self.shodan.credits)
>         logger.info(info_msg)
> 
> def init(self):
>     self.init_shodan_api()
> ```
> `其中def init(self)应更正为`
> def **init**(self)
> `

**Comment by boy-hack** [comment]
插件加载按照Pocsuite3规则来设定的，具体https://github.com/knownsec/pocsuite3/blob/master/docs/CODING.md
如果使用Shodan，使用如下调用 `-r redis_unauthorized_access --dork redis  --plugins=target_from_shodan --max-page 1 --threads 10 -v 2`
