### ISSUE TITLE
在target插件中使用pocsuite3 patch过的requests, 一些特性无效

### ISSUE THREAD

**Issue by ViCrack** [knownsec/pocsuite3#183]
`from pocsuite3.api import requests`
本想在target插件中用一下requests, pocsuite3内置修改过的requests用起来很方便
但是发现一些UA头修改, 禁用SSL校验等功能都无效

发现应该是这里的代码原因
pocsuite3/lib/core/option.py

![图片](https://user-images.githubusercontent.com/18179821/116410986-dabf4c80-a867-11eb-8b7d-462947e62e46.png)
调用target的时间比patch_all还早

是不是要调整下顺序才好

**Comment by pokejeff** [comment]
你好，这个问题确实存在，我们会在下次更新中修复这个bug。
