### ISSUE TITLE
pocsuite3源码方式安装无法运行

### ISSUE THREAD

**Issue by longfeide2008** [knownsec/pocsuite3#190]
按照官方文档http://pocsuite.org/介绍，使用源码方式安装
![image](https://user-images.githubusercontent.com/26161015/119969599-589a8300-bfe1-11eb-8a7e-072383a04e6e.png)

    $ wget https://github.com/knownsec/pocsuite3/archive/master.zip
    $ unzip master.zip

    $ cd pocsuite3
    $ python cli.py --version

pip3 install -r requirements.txt -i https://mirrors.aliyun.com/pypi/simple/

![image](https://user-images.githubusercontent.com/26161015/119975790-dc0ba280-bfe8-11eb-87e7-aa4539f4cd09.png)

在linux下仍然一样
![image](https://user-images.githubusercontent.com/26161015/119983345-9d7ae580-bff2-11eb-94bc-ad2f781a234f.png)

麻烦问下如何解决，可以更新下文档吗？

**Comment by zer0yu** [comment]
我也遇到了类似的问题，现在好像只能 python setup.py install 了才能正常使用

**Comment by LoRexxar** [comment]
如果我没记错的话，第二个报错是因为requests的版本太低了

**Comment by pokejeff** [comment]
这个问题一般需要先安装依赖，后续会更新安装的这部分文档
