### ISSUE TITLE
使用 shodan API-Token 校验失败

### ISSUE THREAD

**Issue by wzqs** [knownsec/pocsuite3#192]
### 环境
```txt
PS C:\Users\> python --version
Python 3.9.2

PS E:\pocsuite3\pocsuite3> python .\cli.py --version

,------.                        ,--. ,--.       ,----.   {1.7.5-ac28d62}
|  .--. ',---. ,---.,---.,--.,--`--,-'  '-.,---.'.-.  |
|  '--' | .-. | .--(  .-'|  ||  ,--'-.  .-| .-. : .' <
|  | --'' '-' \ `--.-'  `'  ''  |  | |  | \   --/'-'  |
`--'     `---' `---`----' `----'`--' `--'  `----`----'   http://pocsuite.org
```
### 问题

输入正确的 API-Token 校验失败：

![image](https://user-images.githubusercontent.com/71961807/120760743-0f00e980-c547-11eb-8612-b0ad8b4a71b1.png)

### 解决

https://raw.githubusercontent.com/knownsec/pocsuite3/master/pocsuite3/modules/shodan/__init__.py

23行 - 25行

```
        if token:
            self.token = token
        self.check_token()
```

修改为：

```
        self.token = token
        if token:
            self.check_token()
```

![image](https://user-images.githubusercontent.com/71961807/120771614-f813c480-c551-11eb-98a5-009bc4778959.png)

PS：不排除是误报，麻烦排查下。

**Comment by pokejeff** [comment]
这个其实是shodan的问题，如果两次请求时间小于一秒的话shodan会返回503错误。改动的代码部分其实影响不大，已在最近的更新中修复。
