### ISSUE TITLE
关于使用pocsuite3 API的问题

### ISSUE THREAD

**Issue by wikiZ** [knownsec/pocsuite3#205]
在使用pocsuite3 API调用时，使用console模式的情况下，能不能提供修改pocs目录的路径的方式，否则，这种情况下，用户需要到pocsuite3的包中添加相关模块，不太方便。
<img width="1036" alt="724db11c79d33bc2948df78528837a0" src="https://user-images.githubusercontent.com/37897216/129502878-71600b1c-3efb-4fd3-8142-f4ec45103f18.png">

**Comment by 13ph03nix** [comment]
已经在 `1.7.8` 版本中支持。

<img width="1412" alt="image" src="https://user-images.githubusercontent.com/17541483/129682453-4be98ae8-0fd0-40f9-9f34-2c636a10bbbd.png">
