### ISSUE TITLE
CODING.md检测 XSS 漏洞出给出案例错误

### ISSUE THREAD

**Issue by saf3d0s** [knownsec/pocsuite3#215]
错误处：https://github.com/knownsec/pocsuite3/blob/master/docs/CODING.md
检测 XSS 漏洞时，payload未md5，但条件判断有md5检测：
    token = random_str()
    payload = 'alert("%s")' % token
    ...

    if hashlib.new('md5', token).hexdigest() in content:
        result['VerifyInfo'] = {}
        result['VerifyInfo']['URL'] = self.url + payload

可以改为：
    if  payload  in content:
        result['VerifyInfo'] = {}
        result['VerifyInfo']['URL'] = self.url + payload

**Comment by 13ph03nix** [comment]
感谢指出，已更正 :)
