### ISSUE TITLE
pip安装完成后，报错module 'collections' has no attribute 'MutableSet'

### ISSUE THREAD

**Issue by bluebluelotus2018** [knownsec/pocsuite3#228]
![image](https://user-images.githubusercontent.com/37805067/143009038-4a6904f5-8cbe-4259-83cf-241a1a1b323e.png)
如图，环境为：win 11 ，python 3.10.0

**Comment by 13ph03nix** [comment]
python3.10 collections 接口改变导致的错误，已经在最新的源码中fix，建议从源码安装最新版本。
