### ISSUE TITLE
当POCBase.get_option()获取空的key时，捕获报错为空

### ISSUE THREAD

**Issue by KagamigawaMeguri** [knownsec/pocsuite3#251]
pocsuite3 1.8.8
演示如下：

```python
class TestPOC(POCBase):
...

    def _verify(self):
        result = {}
        try:
            print(self.get_option("XXXXXXXXX"))
        except Exception as e:
            print('-------这里应该报错---------')
            print(e)
            print('-------这里应该报错---------')
        return self.parse_attack(result)

...
```

![](https://user-images.githubusercontent.com/35628460/145974375-7bfb442b-d5d1-4d9a-980f-5f6c706508ee.png)

不知是否刻意为之，但难免会有ID打成id/Id类似这种低质但确实难以找到情况发生，是否应该输出错误？
感谢回复。

**Comment by 13ph03nix** [comment]
确实有这个问题，当 key 不存在，`raise PocsuiteValidationException` 的时候没有给出错误信息...
建议写代码的时候只捕获那些可能会抛出异常的语句块，比如网络请求
