### ISSUE TITLE
api 梳理

### ISSUE THREAD

**Issue by 13ph03nix** [knownsec/pocsuite3#273]
TODO:

1. requests hook 支持脱离框架使用

**Comment by ltfafei** [comment]
大佬，这个新功能怎么用呢

**Comment by 13ph03nix** [comment]
这个可以代替 requests ，避免 payload 被编码。
https://github.com/urllib3/urllib3/issues/1790

<img width="1412" alt="image" src="https://user-images.githubusercontent.com/17541483/161363583-16bbed9e-448c-4a14-b892-21288b370d87.png">

**Comment by 13ph03nix** [comment]
#289
