### ISSUE TITLE
302跳转时出现 unknown  encoding问题

### ISSUE THREAD

**Issue by saf3d0s** [knownsec/pocsuite3#300]
在使用pocsuite3 测试 kyan run.php 漏洞时,出现unknown encoding:zh-CN问题，相应包如下图：

![image](https://user-images.githubusercontent.com/54883108/179661342-2ecee5ad-d608-440c-aeeb-5f9a04789f70.png)

经排查发现：`pocsuite3\pocsuite3\lib\request\patch\hook_request_redirect.py` 中，`resp.encoding` 会变为 `zh-CN`,导致无法识别改编码。

![image](https://user-images.githubusercontent.com/54883108/179661535-ea652603-1075-4d91-a258-224b828808cc.png)

**Comment by 13ph03nix** [comment]
感谢指出 👍，已修复 :)
