### ISSUE TITLE
The 'mmh3' distribution was not found and is required by pocsuite3

### ISSUE THREAD

**Issue by Axianke** [knownsec/pocsuite3#352]
安装出现报错
The 'mmh3' distribution was not found and is required by pocsuite3

**Comment by 13ph03nix** [comment]
系统是什么发行版？可能是系统版本没有对应的 mmh3 安装包，https://pypi.org/project/mmh3/#files，可以尝试源码手动编译。

**Comment by Axianke** [comment]
windows的装了 c++的环境后又重装了python3.11现在可以了，谢谢
