### ISSUE TITLE
NameError: name 'split_first' is not defined

### ISSUE THREAD

**Issue by N1k0la-T** [knownsec/pocsuite3#368]
```python
from pocsuite3.api import requests
r = requests.get(url='http://192.168.237.132/index.aspx')
```

pocsuite3\lib\request\patch\hook_urllib3_parse_url.py patched_parse_url
NameError: name 'split_first' is not defined

**Comment by N1k0la-T** [comment]
urllib3版本过高

**Comment by iamHuFei** [comment]
哪个版本可以呢

> urllib3版本过高

**Comment by N1k0la-T** [comment]
> 哪个版本可以呢
> 
> > urllib3版本过高

1.26.14
