### ISSUE TITLE
zoomeye api 接口不能用

### ISSUE THREAD

**Issue by ImingI1** [knownsec/pocsuite3#384]
![微信图片_20231130212152](https://github.com/knownsec/pocsuite3/assets/125568577/7798b282-8ca7-4402-a36d-9ffffd01462f)

**Comment by wh0am1i** [comment]
> ![微信图片_20231130212152](https://private-user-images.githubusercontent.com/125568577/286943237-7798b282-8ca7-4402-a36d-9ffffd01462f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE0MjA0ODMsIm5iZiI6MTcwMTQyMDE4MywicGF0aCI6Ii8xMjU1Njg1NzcvMjg2OTQzMjM3LTc3OThiMjgyLThjYTctNDQwMi1hMzZkLTlmZmZmZDAxNDYyZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwMVQwODQzMDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01Y2FmNDIyZGE4MzNmYTdlZGE1YmNiYjFiMzM1M2ZiMGJlYjBlMzAzZTBjYWUyMDA4ZDc3MDY4OTg1YzhjMDU0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.mIxCyoNAsm9OlLbIegveCRDjx0R2rMZlpFmWT1BJ-gg)

在windows 下 token 文件初始化失败，马上修！

**Comment by wh0am1i** [comment]
在windows 的终端里面有 ctrl +v 有概率变成 \x16或者在粘贴的字符串后面追一个 \x16，导致初始化失败。可以尝试更换终端来解决。
