### ISSUE TITLE
加载模块错误

### ISSUE THREAD

**Issue by gp827782797** [knownsec/pocsuite3#4]
☺☻Pocsuite3☺☻ > search think
+-------+--------------------+
| Index |        Path        |
+-------+--------------------+
|   0   | pocs\thinkphp_rce  |
|   1   | pocs\thinkphp_rce2 |
+-------+--------------------+
☺☻Pocsuite3☺☻ > use 0
[12:54:49] [ERROR] load module failed! 'pocs\thinkphp_rce.py'
[12:54:49] [ERROR] No module named 'requests_toolbelt'

**Comment by boy-hack** [comment]
你需要先安装Pocsuite3的依赖 `pip3 install -r requirements.txt`
