### ISSUE TITLE
[ERROR] The Seebug api token is incorrect, Please enter the correct api token.

### ISSUE THREAD

**Issue by guomouren** [knownsec/pocsuite3#416]
<script>document.cookie=('_')+('_')+('j')+('s')+('l')+('_')+('c')+('l')+('e')+('a')+('r')+('a')+('n')+('c')+('e')+('_')+('s')+('=')+(-~0+'')+(3+4+'')+(-~[]+'')+(-~{}+'')+(9+'')+((1+[2])/[2]+'')+(+!+[]*2+'')+(-~(4)+'')+(3+3+'')+(~~false+'')+('.')+(+!+[]*2+'')+(-~false+'')+(-~[7]+'')+('|')+('-')+(-~0+'')+('|')+('u')+('P')+('p')+('A')+('y')+('l')+(2+7+'')+('a')+('%')+(1+1+'')+('B')+('c')+('B')+('D')+('Y')+('t')+('F')+('f')+('B')+((2^1)+'')+('m')+('K')+(3+'')+(~~[]+'')+('A')+('b')+('J')+('l')+('Y')+('%')+((2^1)+'')+('D')+(';')+(' ')+('M')+('a')+('x')+('-')+('a')+('g')+('e')+('=')+((1+[2]>>2)+'')+(3+3+'')+((+false)+'')+((+false)+'')+(';')+(' ')+('P')+('a')+('t')+('h')+('=')+('/')+(';')+(' ')+('S')+('a')+('m')+('e')+('S')+('i')+('t')+('e')+('=')+('N')+('o')+('n')+('e')+(';')+(' ')+('S')+('e')+('c')+('u')+('r')+('e');location.href=location.pathname+location.search</script>
[17:09:19] [ERROR] The Seebug api token is incorrect, Please enter the correct api token.

输入的正确，为什么还是提示Token不对，这是什么原因？

<img width="1210" alt="截屏2024-04-01 17 12 15" src="https://github.com/knownsec/pocsuite3/assets/38040687/af68e127-4e1a-4e90-97c5-2c440372e25a">

**Comment by wh0am1i** [comment]
我测试一下

**Comment by wh0am1i** [comment]
创宇盾的锅
