### ISSUE TITLE
Python.exe stop work appcrash with multithreading

### ISSUE THREAD

**Issue by RussiaVk** [knownsec/pocsuite3#54]
`错误应用程序名称: python.exe，版本: 3.7.3150.1013，时间戳: 0x5cababbb
错误模块名称: python37.dll，版本: 3.7.3150.1013，时间戳: 0x5cabab78
异常代码: 0xc0000005
错误偏移量: 0x0018281a
错误进程 ID: 0x1624
错误应用程序启动时间: 0x01d507fef2991ace
错误应用程序路径: d:\program files (x86)\python37\python.exe
错误模块路径: d:\program files (x86)\python37\python37.dll
报告 ID: 378d56d6-e186-4f59-8eea-007e34f45918
错误程序包全名: 
错误程序包相对应用程序 ID: `

**Comment by boy-hack** [comment]
能否提交更详细的信息，复现步骤等
