### ISSUE TITLE
【咨询】如何将output.fail内容打印在命令行中

### ISSUE THREAD

**Issue by 0x584A** [knownsec/pocsuite3#58]
咨询一下，怎么实现如图中所示的场景：

<img width="1168" alt="Snipaste_2019-06-17_12-02-05" src="https://user-images.githubusercontent.com/14822623/59577842-f009b280-90f7-11e9-98ad-c9c5f5068659.png">

**Comment by boy-hack** [comment]
简单一点就是直接在后面`print`或者
```python
from pocsuite3.api import logger
logger.error('')
```

**Comment by 0x584A** [comment]
> 简单一点就是直接在后面`print`或者
> 
> ```python
> from pocsuite3.api import logger
> logger.error('')
> ```

Nice!!
