### ISSUE TITLE
git clone下来安装报错，pip install 安装也报错，有解决方法吗？

### ISSUE THREAD

**Issue by FakeXing** [knownsec/pocsuite3#79]
clone安装
![image](https://user-images.githubusercontent.com/31611714/63646640-88e82a00-c748-11e9-9755-8aa736afa755.png)

pip install 安装的
![image](https://user-images.githubusercontent.com/31611714/63646660-d6649700-c748-11e9-858c-11ab4c56ee59.png)

是我环境的问题？怎么解决？

**Comment by boy-hack** [comment]
1. `git clone`下来还需要安装依赖`requests` `requests-toolbelt`
2. 你应该使用`pip install pocsuite3 -U`来更新它

**Comment by FakeXing** [comment]
我安装过
![image](https://user-images.githubusercontent.com/31611714/63855852-edb6b500-c9d2-11e9-852e-1d399ffd3d18.png)
