### ISSUE TITLE
通过实例化的方式调用时候，实际上ps内部对requests的补丁是没生效的

### ISSUE THREAD

**Issue by Ro0tk1t** [knownsec/pocsuite3#81]
![2019-08-26 16-33-28 创建的截图](https://user-images.githubusercontent.com/17522269/63677413-80165780-c81f-11e9-8382-b6b15b2ad81e.png)

**Comment by Ro0tk1t** [comment]
实际上还是没生效啊，import方式调用ps的时候，[这里](https://github.com/knownsec/pocsuite3/blob/master/pocsuite3/lib/request/patch/hook_request.py#L11) 的timeout不知道被啥魔法被置为了`None`，程序走到那里后`conf.timeout`里的值已经是`float`类型了

**Comment by boy-hack** [comment]
git pull 更新一下，现在测试是没问题的

**Comment by Ro0tk1t** [comment]
我们这边换了几台机器都是同样的问题，`timeout`还是会被置为None

**Comment by boy-hack** [comment]
确实有问题，一开始没明白你的意思，现在修复了
