### ISSUE TITLE
如何保存output数据到指定的文件？

### ISSUE THREAD

**Issue by sachinly** [knownsec/pocsuite3#89]
使用--plugins html_report.py 生成的报告在~/.pocsuite/output/pocsuite_data_time.html,
如何修改生成报告的路径，和生成报告的文件名？

**Comment by boy-hack** [comment]
修改此处即可 https://github.com/knownsec/pocsuite3/blob/master/pocsuite3/plugins/html_report.py#L169

**Comment by sachinly** [comment]
谢谢，找到修改报告文件名和路劲的方法了。
