### ISSUE TITLE
API调用能中止吗？

### ISSUE THREAD

**Issue by ZZMarquis** [knownsec/pocsuite3#90]
调用 start_pocsuite()开始任务后，有没有一个API可以用来中止本次的扫描呢？

**Comment by ZZMarquis** [comment]
找到一个方法：可以设置kb.thread_continue为False来中止，就是不知道这样做是否有其他影响。

**Comment by boy-hack** [comment]
还没有实现这个api，不过`kb.thread_continue `是一个好方法，或者清空`kb.task_queue`的队列。
