### ISSUE TITLE
Pocsuite3 有没有其他交流平台或者开发者讨论平台？

### ISSUE THREAD

**Issue by Becivells** [knownsec/pocsuite3#92]
问题如标题。issues 不是即时交流有些麻烦

**Comment by boy-hack** [comment]
![WechatIMG106](https://user-images.githubusercontent.com/18695984/68640050-87592180-0541-11ea-9539-622f5c98fd7c.jpeg)
我们临时建立了一个交流群 :-

**Comment by RASSec** [comment]
过期了。

**Comment by caizhuang** [comment]
过期了
